enableStrictSsl: false

nodeLinker: node-modules

npmRegistries:
  //registry.npmjs.org/:
    npmAlwaysAuth: true
    npmAuthToken: 911fe80f-6abc-4248-9c49-b72cc290dcea

npmScopes:
  silenteer:
    npmRegistryServer: "https://registry.npmjs.org/"

yarnPath: .yarn/releases/yarn-1.22.11.cjs
