enableStrictSsl: false

nodeLinker: node-modules

# npmRegistries:
#   //git.tutum.dev/api/v4/packages/npm/:
#     npmAlwaysAuth: true
#     npmAuthToken: TxzFEJFzMM4EgeYoa8YS

# npmScopes:
#   garrio:
#     npmRegistryServer: "https://git.tutum.dev/api/v4/packages/npm/"

yarnPath: .yarn/releases/yarn-1.22.11.cjs
