enableStrictSsl: false

nodeLinker: node-modules

npmRegistries:
  //registry.npmjs.org/:
    npmAlwaysAuth: true
    npmAuthToken: $NPM_CONFIG_TOKEN

npmScopes:
  silenteer:
    npmRegistryServer: "https://registry.npmjs.org/"

yarnPath: .yarn/releases/yarn-1.22.11.cjs
