enableStrictSsl: false

nodeLinker: node-modules

npmRegistries:
  //registry.npmjs.org/:
    npmAlwaysAuth: true
    npmAuthToken: 6eba2b14-1238-4364-aec2-8a07941ff04f

npmScopes:
  silenteer:
    npmRegistryServer: "https://registry.npmjs.org/"

yarnPath: .yarn/releases/yarn-1.22.11.cjs
