enableStrictSsl: false

nodeLinker: node-modules

npmRegistries:
  //registry.npmjs.org/:
    npmAlwaysAuth: true
    npmAuthToken: 9df6e01b-c616-4d1b-980f-9e60e7120a14

npmScopes:
  silenteer:
    npmRegistryServer: "https://registry.npmjs.org/"

yarnPath: .yarn/releases/yarn-1.22.11.cjs
